CREATE TABLE muestreo_viviendas(
  id bigint primary key,
  geom geometry(point,4326),
  Fecha_de_levantamiento Date,
  Nombre_quien_levanto text,
  Codigo text,
  Departamento text,
  Municipio text,
  Ciudad text,
  Barrio_o_Colonia text,
  Aldea_o_Cacerio text,
  Direccion_exacta text,
  Fecha_inicio_del_proyecto Date,
  Fecha_terminacion_del_proyecto Date,
  Nombre_del_beneficiario text,
  Numero_de_identidad text,
  Estado_civil text,
  Nombre_del_conyugue text,
  Numero_de_hijos text,
  Numero _de_telefono text,
  Actividad_laboral_del_beneficiario text,
  Documento_de_propiedad text,
  Sobrecimiento text,
  Solera_inferior text,
  Dado_de_concreto text,
  Castillo text,
  Batientes text,
  Cargadores text,
  Paredes_de_bloque text,
  Puertas text,
  Ventanas text,
  Solera_superior text,
  Techo_de_aluzinc text,
  Clavadores text,
  Piso text,
  Sistema_electrico text,
  Letrina text,
  Ecofogon text,
  Pila text,
  Pintura text,
  Observaciones text,
  fotos text
);
