-- Table: vulnerabilidad_estructural_od3

-- DROP TABLE vulnerabilidad_estructural_od3;

CREATE TABLE vulnerabilidad_estructural_od3
(
  id bigint NOT NULL,
  No_Formulario character varying,
  Fecha_Hora_Visita timestamp without time zone,
  Nombre_Propietario character varying,
  No_Indentidad character varying,
  Telefono character varying,
  Nombre_Arrendatario character varying,
  Calle character varying,
  Bl character varying,
  Lote character varying,
  Barrio character varying,
  Uso_Predominante character varying,
  Estrato_Vivienda character varying,
  Localizacio_Manzana character varying,
  Numero_Pisos_Niveles_sobre_el_terreno character varying,
  Numero_Pisos_Sotanos character varying,
  Numero_Pisos_Total character varying,
  Area_Construida_Primer_Piso character varying,
  Area_Construida_Segundo_Piso character varying,
  Area_Construida_Tercer_Piso character varying,
  Area_Construida_Cuarto_Piso character varying,
  Tenencia_Bien character varying,
  Estado_Construccion character varying,
  Porcentaje_Caso character varying,
  Control_Calidad_Construccion character varying,
  Anos_Construida integer,
  N_Apartamentos_Locales integer,
  N_Familias integer,
  N_Residentes integer,
  N_Anos_Residir_Edificacion integer,
  N_Anos_Residir_Barrio integer,
  Acceso_Edificacion character varying,
  Servicios_Publicos character varying,
  Sometida_Empujes_Tierra character varying,
  Area_Sometida_Deslizamiento character varying,
  Cimentacion character varying,
  Sistema_Entrepiso character varying,
  Sistema_Cubierta character varying,
  Sistema_Estructural character varying,
  Localizacion_Ladera character varying,
  Implantacion_Ladera character varying,
  Causa_Danos character varying,
  Actualmente_Expuesto character varying,
  Exposicion_Deslizamientos character varying,
  Grado_Dano character varying,
  Contacto_Estructura_Expuesta character varying,
  Cimentacion_Danos character varying,
  MurosPortantes_Danos character varying,
  Columnas_Danos character varying,
  Vigas_Danos character varying,
  Entrepisos_Losas_Danos character varying,
  Escaleras_Gradas_Danos character varying,
  Soporte_de_Cubierta_Techos_Danos character varying,
  Cimentacion_Condicion character varying,
  MurosPortantes_Condicion character varying,
  Columnas_Condicion character varying,
  Vigas_Condicion character varying,
  Entrepisos_Losas_Condicion character varying,
  Escaleras_Gradas_Condicion character varying,
  Soporte_de_Cubierta_Techos_Condicion character varying,
  Muros_de_Fachada_o_Antepecho_Danos character varying,
  Paredes_Danos character varying,
  Cubierta_Danos character varying,
  Cielo_Falso_Danos character varying,
  Tanques_elevados_Danos character varying,
  Muros_de_Fachada_o_Antepecho_Condicion character varying,
  Paredes_Condicion character varying,
  Cubierta_Condicion character varying,
  Cielo_Falso_Condicion character varying,
  Tanques_Elevados_Condicion character varying,
  Comentarios_y_Observaciones character varying,
  fotos character varying,
  No_Evaluacion character varying,
  Nombre_y_Apellidos character varying,
  geom geometry(Point,4326),
  CONSTRAINT vulnerabilidad_estructural_od3_pkey PRIMARY KEY (id )
)
WITH (
  OIDS=FALSE
);
ALTER TABLE vulnerabilidad_estructural_od3
  OWNER TO postgres;