CREATE TABLE muestreo_techos(
  id bigint primary key,
  geom geometry(point,4326),
  Fecha_de_levantamiento Date,
  Nombre_quien_levanto text,
  Codigo text,
  Departamento text,
  Municipio text,
  Ciudad text,
  Barrio_o_Colonia text,
  Aldea_o_Cacerio text,
  Direccion_exacta text,
  Fecha_inicio_del_proyecto Date,
  Fecha_terminacion_del_proyecto Date,
  Nombre_del_beneficiario text,
  Numero_de_identidad text,
  Estado_civil text,
  Nombre_del_conyugue text,
  Numero_de_hijos text,
  Numero _de_telefono text,
  Actividad_laboral_del_beneficiario text,
  Documento_de_propiedad text,
  Observaciones text,
  Medida_de_largo text,
  Medida_de_ancho text,
  Medida_de_area_total text,
  fotos text
);
