-- Table: edan_preliminar_od3

-- DROP TABLE edan_preliminar_od3;

CREATE TABLE edan_preliminar_od3
(
  id bigint NOT NULL,
  fecha_hora_reporte timestamp with time zone,
  tipo_de_evento character varying,
  caracteristicas_del_evento character varying,
  fecha_hora_evento timestamp with time zone,
  evento_todavia_en_curso character varying,
  necesidad_apoyo_externo character varying,
  quien_reporta character varying,
  institucion character varying,
  cargo character varying,
  contacto_telefono character varying,
  contacto_email character varying,
  provincia character varying,
  municipio_o_distrito character varying,
  comunidad_o_barrio character varying,
  accesso character varying,
  accesso_por_carretera_vehiculo_4x4 character varying,
  accesso_por_rio_o_mar_barco character varying,
  accesso_por_aire_helicoptero character varying,
  via_de_accesso_recommendada character varying,
  condiciones_meteorologicas character varying,
  efectos_adversos character varying,
  poblacion_salud character varying,
  poblacion_aprox_antes_del_evento integer,
  personas_evacuadadas_desplazadas character varying,
  numero_heridos integer,
  numero_muertos integer,
  numero_desaparecidos integer,
  numero_atrapados integer,
  numero_aislados integer,
  lineas_vitales character varying,
  transporte_carreteras_puentes_otros integer,
  transporte_funcionan integer,
  transporte_funcionan_parcial integer,
  transporte_no_funcionan integer,
  agua_potable_pozos_acueductos_total integer,
  agua_potable_funcionan integer,
  agua_potable_parcial integer,
  agua_portable_no_funcionan integer,
  alcantarillado_sanitario_pluvial_total integer,
  alcantarillado_funcionan integer,
  alcantarillado_parcial integer,
  alcantarillado_no_funcionan integer,
  energia_electrica_total integer,
  energia_electrica_funcionan integer,
  energia_electrica_parcial integer,
  energia_electrica_no_funcionan integer,
  telefonos_flips_total integer,
  telefonos_funcionan integer,
  telefonos_parcial integer,
  telefonos_no_funcionan integer,
  cellulares_total integer,
  cellulares_funcionan integer,
  cellulares_parcial integer,
  cellulares_no_funcionan integer,
  radio_UHF_VHF_total integer,
  radio_funcionan integer,
  radio_parcial integer,
  radio_no_funcionan integer,
  servicios character varying,
  centros_de_salud_total integer,
  centros_de_salud_funcionan integer,
  centros_de_salud_parcial integer,
  centros_de_salud_no_funcionan integer,
  centros_escolares_total integer,
  centros_escolares_funcionan integer,
  centros_escolares_parcial integer,
  centros_escolares_no_funcionan integer,
  numero_viviendas_total integer,
  viviendas_danadas character varying,
  viviendas_destruidas character varying,
  numero_albergues_habilitados_total integer,
  numero_personas_en_albergues integer,
  infraestructura_productiva_primaro character varying,
  infraestructura_productiva_secundario character varying,
  infraestructura_productiva_terciario character varying,
  visita character varying,
  control_de_calidad character varying,
  commentarios character varying,
  fotos character varying,
  geom geometry(MultiPolygon,4326),
  CONSTRAINT edan_preliminar_od3_pkey PRIMARY KEY (id )
)
WITH (
  OIDS=FALSE
);
ALTER TABLE edan_preliminar_od3
  OWNER TO postgres;
